### ISSUE TITLE
Default "lang" option should only get "en", not "en-us"

### ISSUE THREAD

**Issue by goldyfruit** [OpenVoiceOS/ovos-stt-http-server#10]
```
2023-05-30 15:54:15.262 - OVOS - ovos_stt_http_server.gradio_app:bind_gradio_service:27 - WARNING - en-us not in languages, trying ISO 639-1 code
```

**Comment by NeonDaniel** [comment]
These should generally be BCP-47 language codes (though not all plugins comply). This log warns that the plugin didn't advertise `en-us` but then goes on to check `en`. Maybe this should be changed to `INFO` since there isn't really a solid spec stating these are expected BCP-47 and not ISO 639-1 and many STT engines don't have localized models?
